name: Publish

env:
    GH_PKG_URL: "https://maven.pkg.github.com/${{ github.repository }}"

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
    workflow_dispatch:
        inputs:
            version:
                required: true
                description: Version String
                type: string

jobs:
    mc-publish:
        name: Publish Mod to Modrinth - ${{ inputs.version }}
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: true

            -   name: Set up Maven settings for GitHub Packages
                run: |
                    curl -u "${{ secrets.GITHUB_ACTOR }}:${{ secrets.GITHUB_TOKEN }}" -L -o neovelocity-neoforge-${{ inputs.version }}.jar \
                    "${{GH_PKG_URL}}/dev/g_ab/neovelocity/neovelocity-neoforge/${{ inputs.version }}/neovelocity-neoforge-${{ inputs.version }}.jar"

            -   name: List downloaded files
                run: ls -la downloaded

            -   name: Parse changelog
                id: parse-changelog
                run: |
                    changelog=$(cat CHANGELOG.md)
                    list=$(echo "$changelog" | sed -n "/^## \[${{ github.event.release.tag_name }}\]/,/^## \[[0-9]\+\.[0-9]\+\.[0-9a-zA-Z]\+\]/p" | sed -e '1d;$d')
                    echo "$list" > RELEASE_CHANGELOG.md

            -   name: Publish to Modrinth
                uses: Kir-Antipov/mc-publish@v3.3
                with:
                    modrinth-id: RT18TcxA
                    modrinth-featured: true
                    modrinth-unfeature-mode: subset
                    modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
                    version: ${{ inputs.version }}
                    changelog-file: RELEASE_CHANGELOG.md
                    files: |
                        *.jar
                    loaders: neoforge
