name: Mc-Publish

on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
    workflow_dispatch:
        inputs:
            version:
                required: true
                description: Version String
                type: string

jobs:
    mc-publish:
        name: Publish Mod to Modrinth - ${{ inputs.version }}
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: true

            -   name: Download mod file
                run: |
                    curl -u "${{ secrets.GITHUB_ACTOR }}:${{ secrets.GITHUB_TOKEN }}" -L -o neovelocity-neoforge-${{ inputs.version }}.jar \
                    "https://maven.pkg.github.com/${{ github.repository }}/dev/g_ab/neovelocity/neovelocity-neoforge/${{ inputs.version }}/neovelocity-neoforge-${{ inputs.version }}.jar"

            -   name: Parse changelog
                run: |
                    sed -n -e "/^## \[${{ inputs.version }}\]/,/^## \[.*\]/p" CHANGELOG.md | sed '1d;$d' > RELEASE_CHANGELOG.md
                    cat RELEASE_CHANGELOG.md

            -   name: Publish to Modrinth
                uses: Kir-Antipov/mc-publish@v3.3
                with:
                    modrinth-id: RT18TcxA
                    modrinth-featured: true
                    modrinth-unfeature-mode: subset
                    modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
                    version: ${{ inputs.version }}
                    changelog-file: RELEASE_CHANGELOG.md
                    files: |
                        *.jar
                    loaders: neoforge
